add users routes and partials
CodeX-y/photogram-industrial pull request #5
Opened 2024-07-05 22:51 UTC by CodeX-y

2024-07-05 23:59 UTC, CarlosCastanedaDev approved these changes
Nice job, Yusra!

Great use of partials in your views!

2024-07-06 00:00 UTC, CarlosCastanedaDev commented
Please submit your PR link in Canvas so I can grade it and you can move forward.

2024-07-06 01:46 UTC, SaraDawner2000 requested changes
I like how you put everything into partials to improve readibility and save time! There are just a couple of issues with it currently, but they shouldn't be hard to fix

2024-07-06 01:46 UTC, SaraDawner2000 commented on app/controllers/users_controller.rb
You can DRY up the code a little by abstracting fetching the user into a private method and then calling it for all other methods with "before_action"

2024-07-06 01:46 UTC, SaraDawner2000 commented on app/views/users/_navbar.html.erb
great job moving the navbar to a partial!

2024-07-06 01:46 UTC, SaraDawner2000 commented on app/views/users/feed.html.erb
> +<% @users.feed.each do |post| %>
there is a typo: this should be @user.feed. The feed tab doesn't work

2024-07-06 01:46 UTC, SaraDawner2000 commented on app/views/users/_users.html.erb
You could use the "link_to" helper method here

2024-07-06 01:46 UTC, SaraDawner2000 commented on app/views/users/followers.html.erb
The followers tab doesn't load. Your list item partial is named _users.html.erb, in plural. The syntax for rendering it doesn't work. What I found worked was <%= render "users/users", user: user %>

2024-07-06 01:46 UTC, SaraDawner2000 commented on app/views/users/following.html.erb
Same as above

2024-07-07 03:13 UTC, CodeX-y commented on app/views/users/following.html.erb
Thank you so much! I made all the changes you found

2024-07-08 16:49 UTC, merged